### PR TITLE
fixed typo in white card smallbox -> smallpox

### PR DESCRIPTION
**Pull request by BenPortner**
fixed typo in white card smallbox -> smallpox

### CODE REVIEW

**Comment by jakelauer** [comment]
This is actually intentional! https://genius.com/Cards-against-humanity-cards-against-humanity-box-expansion-annotated

**Comment by BenPortner** [comment]
Ha! That's interesting. Yeah, in the box context it makes sense. Still wonder if the pox version would be better for the online version tough. You decide!

**Comment by BenPortner** [comment]
@jakelauer what about the second commit? That is clearly a typo, no?

**Comment by jakelauer** [comment]
Oh yes! Sorry, I had missed that you corrected that as well. My fault! Unfortunate (or fortunately, depending on how you look at it) I'm updating the card sources to a newer set entirely, and adding CardCast support, so integrating this doesn't provide a whole lot of value as the whole set will be swapped out within the week. I really appreciate the PR though, and I'm glad people like you are checking the code out and improving things. Please feel free to continue to do so!

**Comment by BenPortner** [comment]
@jakelauer sure thing Jake! Thanks for putting in the effort to program this in the first place and even host it free for everyone. You're my personal hero of the corona epidemic 👍

**Pull request closed without merging**
